### ISSUE TITLE
Udc - updateLastChangeDate

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#11]
I am going to implement the [nwoolcan.model.brewery.warehouse.Udc](https://github.com/Zeegomo/nwoolcan/blob/master/src/main/java/nwoolcan/model/brewery/warehouse/Udc.java) interface but I don't get the use case of this function. I think it should be a private function called only when the quantity of the Udc gets modified.

**Comment by GiackAloZ** [comment]
Yeah ofc it is like that. We just put that into UML for clarity
