### ISSUE TITLE
Udc - changeState

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#12]
I don't get the use case of this function. I think the UdcState should be final. The Udc shouldn't change its state, but consume some of (or all) its quantity, creating a new Udc with a different state.

**Comment by Zeegomo** [comment]
The state shouldn't be final, as you mentioned in another issue it can become EXPIRED after some time, or consumed if you use it all. Instead i suggest that there is no method changeState() available from outside the class and the class itself handles the change of the state based of the conditions

**Comment by samueleceroni** [comment]
I think that a dynamical approach would be better: the state stored is final, but when getState() is called, if the expiration date is passed and the state is 'available', it returns an 'expired' state, otherwise it returns the stored final state.
There is no cases in which a udc is used only in part: if a part of it is consumed you want to transfer that amount to another udc with state consumed.

**Comment by Zeegomo** [comment]
I don't like the idea of a state being final, it's counterintuitive. The idea of a state is that it holds current info, if the state does not change then we do not need a state

**Comment by samueleceroni** [comment]
actually you're right. apparently the state won't be final, because it can dynamically change from available to expired. I will think about how to approach this.
