### ISSUE TITLE
UdcState - EXPIRED entry

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#14]
I would like to add this entry which is returned by Udc.getState() in case the expiration date is passed.

**Comment by Zeegomo** [comment]
nice

**Comment by GiackAloZ** [comment]
Do you understand that you have to regularly check the expiration date of a Udc in order for this state to be change accordingly?

**Comment by samueleceroni** [comment]
Sure, see the related issue
"when getState() is called, if the expiration date is passed and the state is 'available', it returns an 'expired' state, otherwise it returns the stored final state."
