### ISSUE TITLE
View.Utils is too big

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#169]

**Comment by GiackAloZ** [comment]
remember to put a description for @Carlovan and some labels and maybe assign this to the project

**Comment by samueleceroni** [comment]
@Carlovan i think the view package is too big. I created the pr #170 to fix this, creating the view.utils subpackage.

**Comment by samueleceroni** [comment]
I think that it is still too big. I don't see the need to keep the subpackage master table and subview in the first directory
