### ISSUE TITLE
Add method to return also class controller in ViewManager

### ISSUE THREAD

**Issue by Zeegomo** [Zeegomo/nwoolcan#180]
something like ```        final FXMLLoader loader = new FXMLLoader(ViewType.class.getResource(type.getResourceName()));
        return Results.ofChecked(() -> {
            this.injectIntoController(loader);
            final Parent parent = loader.load();
            loader.<InitializableController<T>>getController().initData(viewModel);
            return Pair.of(parent, loader.<U>getController());
        }).peekError(err -> Logger.getGlobal().severe(err.toString() + "\n" + err.getCause()));
    }```

**Comment by GiackAloZ** [comment]
dont say what you need, say why you need it
