### ISSUE TITLE
reload when calling getpreviousview()

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#186]
Hi, I would need this feature: I should be able to call a reload method when my interface is displayed as a consequence of the previousView method calls.. Do you think it is doable? It would be quite urgent..

**Comment by Carlovan** [comment]
There are several methods:

- pop the current view and push another one, built with the new (I think you have a new) view model: this is really easy to do and the only overhead I see is the actual loading of the FXML, but keep in mind that the state of every control will reset (like text inputs, combo boxes...)
- use the Observer pattern for example with [properties](https://docs.oracle.com/javafx/2/binding/jfxpub-binding.htm) in your view model so the view always displays the updated values; this is really flexible and powerful but requires quite abit of work I guess
- after solving #180 you can keep the controller when loading the fxml and then call its initData when you need to reload

**Comment by samueleceroni** [comment]
in order to fix this, I will pass as detail parameter a pair<detail, runnable> so that the subview can call the runnable (containing the update function)..
