### ISSUE TITLE
Avoid use of ternary operator if favor of Result functional methods

### ISSUE THREAD

**Issue by Zeegomo** [Zeegomo/nwoolcan#19]
#18 Related
[remove](https://github.com/Zeegomo/nwoolcan/pull/18/files#diff-c15780fbb60a40360f3fa31925bf025c) should use functional methods of Result instead of ternary operator in order to make code more readable and consistent.
In particular the use of the `require` function could help here

**Comment by GiackAloZ** [comment]
#20 this should fix this issue
