### ISSUE TITLE
Add filters to master table

### ISSUE THREAD

**Issue by Carlovan** [Zeegomo/nwoolcan#214]

**Comment by Carlovan** [comment]
Can you @GiackAloZ @samueleceroni @Zeegomo tell me which filters you need?

**Comment by GiackAloZ** [comment]
I need a `TextFilter`, a `DateFilter`, a `ComboBoxFilter` and maybe a `CheckBoxFilter` for boolean filtering

**Comment by GiackAloZ** [comment]
The `ComboBoxFilter` is like a filter which you can choose a value from a list of values
