### ISSUE TITLE
Default quantity unit of measure in Article

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#30]
Since we already decided to associate only one unit of measure to each article I would like to make this association strong and explicit by putting a field in Article where we decide which unit of measure is used by it.
Otherwise I was thinking about associate each article to a type of unit of measure (eg Volume, weight, units etc.) and to implement a function in Unit of measure to check if the uom is of the correct category (eg if kilogram is weight, Liter is volum etc.). I think this second solution lets us more free to add new Unit of measure (or subunit of measure like grams or decagram) in the future.
Please let me know what you think about this, I wouldn't like to "solve this by myself".
Thanks :kiss:

**Comment by Zeegomo** [comment]
I like the second option more, even if we already stated that we aren't going to implement any uom other than the standard one.

**Comment by GiackAloZ** [comment]
I like the idea, but, in this case, I think I'll add a field to the current `enum UnitOfMeasure` of type `enum PhysicalQuantity` (which is the english translation of "grandezza fisica") and his getter.
Maybe we can even think, (at this point) how to interchange between same physical quantities (like a ratio or something like that)

**Comment by samueleceroni** [comment]
For my only purpose, in order to verify whether a record is compatible with the current stock, it will be enough to do the operation between the two quantities and check the returning result, so I don't need such functions like "isCompatible(Quantity other)". Concerning new unit of measure they can be managed in the view controller.
