### ISSUE TITLE
Proposed new methods for Result/Results

### ISSUE THREAD

**Issue by Zeegomo** [Zeegomo/nwoolcan#34]
I think some new methods for `Results` could come in handy.
In particular:
*  `requireNonNull(T elem): Result<T>` as a non static method for `Result`
* `requireNonNull(Object o...): Result<Empty>` as a static method for `Results` that return a `Result<Empty>` holding  an `Empty` instance if every object provided as argument is not null, otherwise a `NullPointerException`

What do you think of this?

**Comment by GiackAloZ** [comment]
It can be useful yes. I would use it

**Comment by Zeegomo** [comment]
Still have some doubts...
As you can see most of the times we check for multiple values not being null we also provide different error messages for every value, this is not possible with the proposed `requireNonNull(Object o...)`, does it still make sense? Do we want to enforce the use of `requireNonNull(T elem)` with personalized error message?

**Comment by GiackAloZ** [comment]
you can make `requireNotNull` a instance fluent method instead

**Comment by Zeegomo** [comment]
It is fluent already

**Comment by GiackAloZ** [comment]
yeah but not an instance one

**Comment by Zeegomo** [comment]
Yes, I mean we probably need only the first proposed method:
`requireNonNull(Object o)` and `requireNonNull(Object o, String errorMessage)` in the `Result` class that return a `NullPointerException` (with optional message) wrapped in a `Result` if the object is null

**Comment by GiackAloZ** [comment]
yes
