### ISSUE TITLE
Negative value don't include zero

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#39]
In QuantityChecker class if a value is not greater than zero, an exception is thrown. It should be thrown only when the number is not greater or equal than zero.

**Comment by GiackAloZ** [comment]
It is intentional to have the possibility to create an empty quantity, but it can be refactored so quantities cannot be empty.

**Comment by samueleceroni** [comment]
I meant that I need empty quantity, but now it is not allowed to have it.

**Comment by GiackAloZ** [comment]
Oh ok I got it wrong. Of course it's a typo :)
