### ISSUE TITLE
Quantity is broken.

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#42]
When adding or removing something it cast the result to BigDecimal. After this, when i call equals on two quantities where the first has an Integer representation of 1 and the second has a BigDecimal representation of 1, they won't ever be equal one another.

**Comment by GiackAloZ** [comment]
Can you please create a fix branch and add tests that should pass?
I'll fix the issue and make them pass :)

**Comment by GiackAloZ** [comment]
I fixed it, you can try to test it.
