### ISSUE TITLE
Common standard for null check

### ISSUE THREAD

**Issue by Zeegomo** [Zeegomo/nwoolcan#57]
I think we need a common standard for null checks. Currently we both use Objects and Result for `requireNonNull`, when should we prefer one over the other?

**Comment by Zeegomo** [comment]
I'll suggest using [this](https://github.com/uber/NullAway) for this type of checks. NullAway check for null at **compile** time, preventing controls at runtime.

**Comment by GiackAloZ** [comment]
Do we need to also remove all `requireNonNull` usage?

**Comment by Zeegomo** [comment]
I should have removed usages of requireNonNull in the code but I left the
function in the Result class, if we see there's no other use case i will
remove that as well

Il dom 10 mar 2019, 12:29 Giacomo Aloisi <notifications@github.com> ha
scritto:
