### ISSUE TITLE
date rounding

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#60]
actually we should change how we save dates. In records, we should round it to minutes, whilst regarding expiration dates we should round them to days.
Just an example on how to do it:
`Date nearestMinute = DateUtils.round(new Date(), Calendar.MINUTE);`

**Comment by samueleceroni** [comment]
I am just taking a look at the [Date](https://docs.oracle.com/javase/8/docs/api/java/util/Date.html) class. I see that most of the methods are deprecated. I would suggest to switch to [Calendar](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html) instead.
Regarding the date rounding I would create a DateUtils/CalendarUtils in order to do it, in the project 'util' folder.
Please let me know your thoughts.
PS. the previously quoted 'DateUtils.round(...)' is not present in the standard libraries. It is in the Apache commons-lang.

**Comment by Zeegomo** [comment]
If you need the Apache library you can import it in the gradle config, just make sure to link the smallest package that contains what you need for now as we don't need the whole commons-lang. Other than that, I think it makes no difference, you can pick whatever you want.

**Comment by samueleceroni** [comment]
I will just import it and apply the rounding. I leave the issue opened until I will change it.
