### ISSUE TITLE
QueryClasses

### ISSUE THREAD

**Issue by samueleceroni** [Zeegomo/nwoolcan#68]
I really like the idea to use the queryClass pattern (or whatever it is called), but I think that most of the QueryClasses will have many queries in common.. Wouldn't it be better an abstract class common to all the query classes?
Common methods follow:

    Optional<Number> getGreaterThanValue();
    Optional<Number> getLessThanValue();
    Optional<Number> getExactValue();
    Optional<Date> getStartDate();
    Optional<Date> getEndDate();
    boolean isSortByValue();
    boolean isSortByDate();
    boolean isSortDescending();

please let me know what you think about it.

**Comment by GiackAloZ** [comment]
Query classes are too specific and no need for having a common class
