### ISSUE TITLE
Change name of method "getBatchSize()" in "BatchInfo"

### ISSUE THREAD

**Issue by GiackAloZ** [Zeegomo/nwoolcan#90]
Seems like this method updates every time the batch changes his size, but it does not and (as previously stated) if should not since it's referred to the initial size.
Can we change it's name to "getInitialBatchSize()" or at least the javadoc stating it is in fact the initial size?

**Comment by Zeegomo** [comment]
Where do you get that it changes every time the batch changes its size? It seems to me that the field is `final` and therefore never modified.

**Comment by GiackAloZ** [comment]
From the name, not the code.
You should understand from the interface, not from looking at the implementation code.
I'm just saying for a user like me it is possible to misunderstand the concept of this method.
I think at least javadoc in the interface should be changed.
